### ISSUE TITLE
Configuration information needed. 

### ISSUE THREAD

**Issue by AtlantaKid** [sailhenz/terminal-ssh#1]
In your documentation you are simply saying:
Create user setting
"ssh.server": {
    "servername": "savina",
    "host": "savina",
    "username": "savina",
    "password": "savina"
}

--- What JSON file does this go in and how do I navigate to it, I understand that I need to change the values with my own, but I can not figure out which file this gets added in.
thanks

**Comment by sailhenz** [comment]
Click the gear icon (bottom left) and select settings and user settings window will appear. 

Just put the settings on the right pane under 
```
"Place your settings here to overwrite the Default Settings."
{
   "ssh.server": {
      "servername": "savina",
      "host": "savina",
      "username": "savina",
      "password": "savina"
   }
}
```

**Comment by Chaos2356** [comment]
I don't understand how to do this... Can you show a screenshot?
