### ISSUE TITLE
Unknown configuration setting "ssh.server"

### ISSUE THREAD

**Issue by l2dev** [sailhenz/terminal-ssh#2]
When I add configs to my user settings I get error saying "Unknown configuration setting"

**Comment by sailhenz** [comment]
Can I have the steps to replicate the issue? I also suggest to update vscode to 1.24 and up.

**Comment by l2dev** [comment]
I had the latest vscode. Only steps I did was installing the plugin and
then tried to add configuration and was not able to. Not really sure how
else can I help.

**Comment by sailhenz** [comment]
1) close vscode. 
2) go to the .vscode\extensions\sailhenz.terminal-ssh-0.2.1 (usually under C:\Users\<username>  
3) install the plugin manually (npm install)
4) open vscode and run the plugin otherwise put the cursor in the integrated terminal and press `CTRL+.`
